name: Release

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    env:
      PROJECT_FILE: PublicAI.Net/PublicAI.Net.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack "$PROJECT_FILE" --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersion }}

      - name: Push to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.gitversion.outputs.FullSemVer }}
          name: Release ${{ steps.gitversion.outputs.FullSemVer }}
          body: |
            📦 NuGet package version **${{ steps.gitversion.outputs.NuGetVersion }}** published.

            Commit: ${{ github.sha }}
          files: ./artifacts/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
